name: Terraform Apply Changes

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
  workflow_dispatch:  # allows manual trigger too

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      TF_VERSION: 1.6.6

    defaults:
      run:
        working-directory: ./terraform  # Change if your .tf files live elsewhere

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan
        continue-on-error: true

      - name: Check for Changes
        id: check_changes
        run: |
          if grep -q 'No changes. Infrastructure is up-to-date.' <<< "$(terraform show -no-color tfplan)"; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Terraform Apply
        if: steps.check_changes.outputs.no_changes == 'false'
        run: terraform apply -auto-approve tfplan

